[phases.setup]
nixPackages = ['nodejs_20', 'npm-10_x', 'openssl']

[phases.install]
cmds = ['npm install --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node dist/index.js'